import type { StudyPlan, StudyTask } from '@/lib/supabase';

export function exportPlanToPDF(plan: StudyPlan, tasks: StudyTask[]) {
  const completedCount = tasks.filter((t) => t.completed).length;
  const progress = tasks.length > 0 ? Math.round((completedCount / tasks.length) * 100) : 0;

  const examDate = new Date(plan.exam_date + 'T00:00:00').toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const tasksByDay = tasks.reduce<Record<number, StudyTask[]>>((acc, task) => {
    if (!acc[task.day_number]) acc[task.day_number] = [];
    acc[task.day_number].push(task);
    return acc;
  }, {});
  const dayNumbers = Object.keys(tasksByDay).map(Number).sort((a, b) => a - b);

  const dayRows = dayNumbers
    .map((dayNum) => {
      const dayTasks = tasksByDay[dayNum];
      const taskRows = dayTasks
        .map(
          (task) =>
            `<tr><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;">${task.title}</td><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;">${task.topic}</td><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;text-align:center;">${task.duration_minutes}m</td><td style="padding:6px 12px;border-bottom:1px solid #e2e8f0;text-align:center;">${task.completed ? 'Done' : 'Pending'}</td></tr>`
        )
        .join('');
      const firstTask = dayTasks[0];
      const date = new Date(firstTask.task_date + 'T00:00:00').toLocaleDateString('en-US', {
        month: 'short',
        day: 'numeric',
      });
      return `<tr style="background:#f1f5f9;"><td colspan="4" style="padding:8px 12px;font-weight:600;color:#1e40af;">Day ${dayNum} — ${date}</td></tr>${taskRows}`;
    })
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Study Plan — ${plan.subject}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 40px; color: #1e293b; }
  .header { text-align: center; margin-bottom: 32px; }
  .header h1 { font-size: 28px; color: #1e40af; margin: 0 0 4px; }
  .header p { color: #64748b; margin: 0; }
  .info-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; margin-bottom: 32px; }
  .info-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; text-align: center; }
  .info-card .label { font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; color: #64748b; margin-bottom: 4px; }
  .info-card .value { font-size: 18px; font-weight: 600; color: #1e293b; }
  .progress-bar { height: 12px; background: #e2e8f0; border-radius: 6px; overflow: hidden; margin: 16px 0; }
  .progress-fill { height: 100%; background: linear-gradient(90deg, #3b82f6, #1d4ed8); border-radius: 6px; width: ${progress}%; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; }
  th { text-align: left; padding: 8px 12px; background: #1e40af; color: white; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; }
  .footer { margin-top: 32px; text-align: center; color: #94a3b8; font-size: 12px; }
</style>
</head>
<body>
  <div class="header">
    <h1>Smart Study Planner AI</h1>
    <p>Personalized Study Plan</p>
  </div>
  <div class="info-grid">
    <div class="info-card"><div class="label">Subject</div><div class="value">${plan.subject}</div></div>
    <div class="info-card"><div class="label">Exam Date</div><div class="value">${examDate}</div></div>
    <div class="info-card"><div class="label">Study Hours / Day</div><div class="value">${plan.daily_hours} hrs</div></div>
  </div>
  <div style="margin-bottom:24px;">
    <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
      <span style="font-weight:600;color:#1e293b;">Progress</span>
      <span style="font-weight:600;color:#1e40af;">${completedCount} / ${tasks.length} tasks (${progress}%)</span>
    </div>
    <div class="progress-bar"><div class="progress-fill"></div></div>
  </div>
  <table>
    <thead>
      <tr><th>Task</th><th>Topic</th><th style="text-align:center;">Duration</th><th style="text-align:center;">Status</th></tr>
    </thead>
    <tbody>
      ${dayRows}
    </tbody>
  </table>
  <div class="footer">Generated by Smart Study Planner AI</div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 500);
  }
}
