import LegalPageLayout from '@/components/LegalPageLayout';

type TermsOfServiceProps = {
  onBack: () => void;
};

export default function TermsOfService({ onBack }: TermsOfServiceProps) {
  return (
    <LegalPageLayout title="Terms of Service" icon="file" onBack={onBack}>
      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">1. Acceptance of Terms</h2>
        <p>
          Welcome to Smart Study Planner AI. By creating an account or using this application, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the application.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">2. Description of Service</h2>
        <p>
          Smart Study Planner AI is a study planning application that generates personalized study schedules based on your subjects, exam dates, and available study hours. The service includes an AI study assistant, progress tracking, motivational tips, and PDF export of study plans. The application is provided as a tool to support your learning and is not a substitute for professional educational advice.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">3. User Accounts</h2>
        <ul className="list-disc pl-6 space-y-2">
          <li>You must provide a valid email address and password to create an account.</li>
          <li>You are responsible for maintaining the confidentiality of your password and for all activities that occur under your account.</li>
          <li>You must be at least 13 years old to create an account.</li>
          <li>You agree to notify us immediately of any unauthorized use of your account.</li>
          <li>You can delete your account and all associated data at any time through the Settings page.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">4. Acceptable Use</h2>
        <p className="mb-3">You agree to use the application only for its intended purpose. You will not:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Use the service for any illegal or unauthorized purpose.</li>
          <li>Attempt to access another user's data or account.</li>
          <li>Interfere with or disrupt the service, servers, or networks connected to the application.</li>
          <li>Use automated tools to scrape, harvest, or collect data from the application.</li>
          <li>Upload or transmit any content that is unlawful, harmful, or infringes on the rights of others.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">5. Your Data and Privacy</h2>
        <p className="mb-3">Your use of the application is also governed by our Privacy Policy. Key points:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>Your email is used only for authentication and associating your study data with your account.</li>
          <li>Your personal data is never sold or shared with third parties.</li>
          <li>Your study plans and tasks are private and accessible only to you.</li>
          <li>You can delete your account and all data at any time.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">6. AI-Generated Content</h2>
        <p>
          The study plans and AI assistant responses are generated by automated algorithms and may not always be accurate or suitable for your specific situation. You are responsible for evaluating the suggestions provided and adapting them to your needs. We do not guarantee any specific academic results from using the application.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">7. Intellectual Property</h2>
        <p>
          The application, including its design, code, features, and branding, is the intellectual property of its developer. You retain ownership of the study plans and data you create. You may not copy, modify, or distribute the application's code or design without permission.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">8. Disclaimer of Warranties</h2>
        <p>
          The application is provided "as is" and "as available" without warranties of any kind, whether express or implied. We do not guarantee that the service will be uninterrupted, error-free, or completely secure. Your use of the application is at your own risk.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">9. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, we shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the application, including but not limited to loss of data, study plans, or academic performance. Your study data is stored securely, but you are encouraged to export important plans using the PDF download feature.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">10. Account Termination</h2>
        <p>
          You may delete your account at any time through Settings. We reserve the right to suspend or terminate accounts that violate these Terms of Service or engage in harmful behavior. Upon termination, your data will be permanently deleted.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">11. Changes to These Terms</h2>
        <p>
          We may update these Terms of Service from time to time. When we do, we will revise the "Last updated" date at the top of this page. Continued use of the application after changes are made constitutes your acceptance of the updated terms.
        </p>
      </section>

      <section>
        <h2 className="text-xl font-semibold text-slate-800 dark:text-white mb-3">12. Contact</h2>
        <p>
          If you have any questions about these Terms of Service, please reach out through the About page of the application.
        </p>
      </section>
    </LegalPageLayout>
  );
}
